### ISSUE TITLE
Memory leak found, is there any solution of it ?

### ISSUE THREAD

**Issue by riksof-abdulrauf** [GyazSquare/GSLCSVSerialization#2]
Memory leak found, is there any solution of it ?
I am reading 5000 lines csv file, its causing issue of memory leak please check attached images with memory usage
![screen shot 2017-02-20 at 5 33 51 pm](https://cloud.githubusercontent.com/assets/5626513/23125337/10488720-f793-11e6-9a12-121647c4996d.png)

![screen shot 2017-02-20 at 5 34 09 pm](https://cloud.githubusercontent.com/assets/5626513/23125339/1302ce1c-f793-11e6-8145-1e01984e7d83.png)

**Comment by gooichi** [comment]
Thank you for your report and I'm sorry for my late reply.

I have checked leaks using Instruments. No leaks were found and heap memory has not continued to increase. (Ref: [Instruments User Guide - About Memory Analysis](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/InstrumentsUserGuide/CommonMemoryProblems.html#//apple_ref/doc/uid/TP40004652-CH91-SW1))

I attached my sample program below. You can compile it with the following command.

```shell
$ xcrun clang main.m path/to/GSLCSVSerialization.m -Ipath/to/GSLCSVSerialization -fmodules -fobjc-arc -framework Foundation
```

I close this issue. If you have any problems, please reopen this.

```objc
@import Foundation;

#import "GSLCSVSerialization.h"

int main() {
    @autoreleasepool {
        NSUserDefaults *userDefaults = [NSUserDefaults standardUserDefaults];
        NSString *path = [userDefaults stringForKey:@"path"];
        NSString *encodingName = [userDefaults stringForKey:@"encoding"];
        CFStringEncoding cfEncoding = CFStringConvertIANACharSetNameToEncoding((__bridge CFStringRef)encodingName);
        NSStringEncoding encoding = (cfEncoding != kCFStringEncodingInvalidId) ? CFStringConvertEncodingToNSStringEncoding(cfEncoding) : [NSString defaultCStringEncoding];
        NSError *error = nil;
        NSData *data = [NSData dataWithContentsOfFile:path options:0 error:&error];
        if (!data) {
            NSLog(@"%@", error);
            return 1;
        }
        for (NSInteger i = 0; i < 10; i++) {
            @autoreleasepool {
                NSError *error = nil;
                NSArray<NSArray<NSString *> *> *records = [GSLCSVSerialization CSVRecordsWithData:data encoding:encoding options:0 error:&error];
                if (!records) {
                    NSLog(@"%@", error);
                    return 1;
                }
                NSLog(@"PASS %@: rows=%@", @(i + 1), @(records.count));
            }
        }
    }
    return 0;
}
```
